# Generated by Django 3.1.2 on 2023-05-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idjuego', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('existencias', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
